# Generated by Django 2.2 on 2019-04-09 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pokemon',
            options={'verbose_name_plural': 'pokemon'},
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='id',
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='pokemon_number',
            field=models.CharField(max_length=3, primary_key=True, serialize=False),
        ),
    ]
