# Generated by Django 2.2 on 2019-04-18 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0002_auto_20190409_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='pokemon_image',
            field=models.URLField(blank=True),
        ),
    ]
